from extensions import db


class ZParte(db.Model):
    __tablename__ = 'zparte'

    # Clave primaria compuesta
    MANDT = db.Column(db.BigInteger, primary_key=True)
    PERNR = db.Column(db.String(8), primary_key=True)
    PADAT = db.Column(db.Date, primary_key=True)
    TIPO = db.Column(db.String(1), primary_key=True)
    TURNO = db.Column(db.String(1), primary_key=True)

    REDAT = db.Column(db.Date, nullable=True)
    UPDAT = db.Column(db.Date, nullable=True)
    MODIF = db.Column(db.String(1), nullable=True)
    MES = db.Column(db.String(2), nullable=True)
    EJERC = db.Column(db.String(4), nullable=True)
    STAT = db.Column(db.String(1), db.ForeignKey('eppartstatus.STATUS'), nullable=True)
    TPRE1 = db.Column(db.String(4), nullable=True)
    TPRE2 = db.Column(db.String(4), nullable=True)
    PAJOB = db.Column(db.String(1), nullable=True)
    CODGR = db.Column(db.Integer, default=0)
    DPTO = db.Column(db.String(150), nullable=True)
    CATEG = db.Column(db.String(20), nullable=True)
    TREALIZ = db.Column(db.String(35), nullable=True)
    TIPODIA = db.Column(db.String(1), nullable=True)
    PERNRCR = db.Column(db.String(8), nullable=True)
    CRDAT = db.Column(db.Date, nullable=True)
    PERNRVB = db.Column(db.String(8), nullable=True)
    VBDAT = db.Column(db.Date, nullable=True)
    PERNRFI = db.Column(db.String(8), nullable=True)
    FIDAT = db.Column(db.Date, nullable=True)
    PERNRHR = db.Column(db.String(8), nullable=True)
    HRDAT = db.Column(db.Date, nullable=True)

    # Métricas de horas
    HN = db.Column(db.Integer, default=0)
    HP = db.Column(db.Integer, default=0)
    DL = db.Column(db.Integer, default=0)
    DF = db.Column(db.Integer, default=0)
    NL = db.Column(db.Integer, default=0)
    NF = db.Column(db.Integer, default=0)
    DLB = db.Column(db.Integer, default=0)
    DFB = db.Column(db.Integer, default=0)
    NLB = db.Column(db.Integer, default=0)
    NFB = db.Column(db.Integer, default=0)
    DLF = db.Column(db.Integer, default=0)
    DFF = db.Column(db.Integer, default=0)
    NLF = db.Column(db.Integer, default=0)
    NFF = db.Column(db.Integer, default=0)
    DLC = db.Column(db.Integer, default=0)
    DFC = db.Column(db.Integer, default=0)
    NLC = db.Column(db.Integer, default=0)
    NFC = db.Column(db.Integer, default=0)
    LLDL = db.Column(db.Integer, default=0)
    LLDF = db.Column(db.Integer, default=0)
    LLNL = db.Column(db.Integer, default=0)
    LLNF = db.Column(db.Integer, default=0)
    DLCO = db.Column(db.Integer, default=0)
    DFCO = db.Column(db.Integer, default=0)
    NLCO = db.Column(db.Integer, default=0)
    NFCO = db.Column(db.Integer, default=0)
    DLBN = db.Column(db.Integer, default=0)
    DFBN = db.Column(db.Integer, default=0)
    NLBN = db.Column(db.Integer, default=0)
    NFBN = db.Column(db.Integer, default=0)
    DLCOP = db.Column(db.Integer, default=0)
    DFCOP = db.Column(db.Integer, default=0)
    NLCOP = db.Column(db.Integer, default=0)
    NFCOP = db.Column(db.Integer, default=0)

    # Motivos
    MOTIVOHE = db.Column(db.String(150), nullable=True)
    MOTIVOHEB = db.Column(db.String(150), nullable=True)
    MOTIVOHP = db.Column(db.String(150), nullable=True)
    MOTIVOHEC = db.Column(db.String(150), nullable=True)
    MOTIVOLLA = db.Column(db.String(150), nullable=True)
    MOTIVOHFM = db.Column(db.String(150), nullable=True)
    MOTHECO = db.Column(db.String(150), nullable=True)
    MOTHEBNP = db.Column(db.String(150), nullable=True)
    MOTHECOP = db.Column(db.String(150), nullable=True)

    # Indicadores CHAR(1)
    SP = db.Column(db.String(1), nullable=True)
    CP = db.Column(db.String(1), nullable=True)
    PP = db.Column(db.String(1), nullable=True)
    B = db.Column(db.String(1), nullable=True)
    D = db.Column(db.String(1), nullable=True)
    DD = db.Column(db.String(1), nullable=True)
    KM = db.Column(db.Integer, nullable=True)
    P52 = db.Column(db.String(1), nullable=True)
    P60 = db.Column(db.String(1), nullable=True)
    BLV = db.Column(db.String(1), nullable=True)
    BSDF = db.Column(db.String(1), nullable=True)
    CPT = db.Column(db.String(1), nullable=True)
    PN = db.Column(db.String(1), nullable=True)
    PA = db.Column(db.String(1), nullable=True)
    NI020 = db.Column(db.String(1), nullable=True)
    OBSERV = db.Column(db.String(150), nullable=True)
    SUST = db.Column(db.String(1), nullable=True)
    SUPERN = db.Column(db.String(8), nullable=True)
    SUPERN1 = db.Column(db.String(8), nullable=True)
    MOTIVOSUST = db.Column(db.String(150), nullable=True)
    NH = db.Column(db.Integer, default=0)
    OBSERV1 = db.Column(db.String(150), nullable=True)
    HNDEC = db.Column(db.String(6), default='000000')
    TIPOTURNO = db.Column(db.Integer, default=0)
    TELETRABAJO = db.Column(db.String(1), default='f')
    DESCANSO = db.Column(db.String(1), default='f')
    ART21DESC = db.Column(db.String(1), default='f')
    TURNOSUSTIT = db.Column(db.String(80), nullable=True)
    USER_ID = db.Column(db.String(8), nullable=False, default='00000000')
    PERVBDE = db.Column(db.String(8), nullable=True)
    PERFIDE = db.Column(db.String(8), nullable=True)
    STATPREV = db.Column(db.String(1), default='')